spring:
  application:
    name: products
  mongodb:
    uri: mongodb+srv://root:csh123@chilankash.wpeuqrw.mongodb.net/?appName=ChilankaSH
    database: product-reviews
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs